export default {
  lineas: [
    "ABULON",
    "ADQ. MAQUINARIA",
    "ALFALFA",
    "ALGODON",
    "ALGODON Y TRIGO",
    "APICOLA",
    "AVICOLA",
    "CAMARON",
    "CARACOL",
    "CARTAMO",
    "CEBADA",
    "CITRICOS",
    "ESCAMA",
    "FACTORAJE",
    "FERTILIZANTE",
    "GANADO",
    "HORTALIZAZ",
    "INFRAESTRUCTURA Y EQUIPO",
    "INVERNADEROS",
    "LECHUGA Y CEBOLLA",
    "LENGUADO",
    "MAIZ",
    "OLIVO",
    "OSTION",
    "OTROS",
    "PAGO DE PASIVO",
    "PROCAMPO",
    "PROFER",
    "REP. MAQUINARIA",
    "SANDIA Y TOMATE",
    "SORGO",
    "SUDAN",
    "TOMATE",
    "TRIGO",
    "VID",
    "CEBADA Y SORGO",
    "ENTUBADO DE CANAL",
    "FLORICULTURA",
    "CEBOLLA",
    "RYE-GRASS",
    "CAPITAL DE TRABAJO",
    "AVENA"
  ],
  actividades: [
    "AGRICULTURA",
    "GANADERA",
    "PESCA",
    "COMERCIAL",
    "FORESTAL"
  ],
  unidades: [
    "PROYECTO",
    "HECTAREAS",
    "TONELADAS",
    "CABEZA",
    "PESOS",
    "PIEZA",
    "UNIDAD"
  ],
  destinos: [
    "ADQUISICION DE MATERIA PRIMA",
    "CAPITAL DE TRABAJO",
    "ADQUISICION DE MAQUINARIA Y EQUIPO",
    "CONSTRUCCION Y ADQUISICION DE INFRAESTRUCTURA",
    "MODERNIZACION DE INFRAESTRUCTURA",
    "FACTORAJE",
    "REPARACION DE MAQUINARIA Y EQUIPO",
    "PAGO DE PASIVO"
  ],
  tenencias: [
    "COLONO",
    "PEQUEÑO PROPIETARIO",
    "EJIDATARIO",
    "ARRENDATARIO"
  ]

  




}